import { Swiper, SwiperSlide } from "swiper/react";
import "swiper/css";
import "swiper/css/pagination";
import "swiper/css/navigation";
import { Navigation, Autoplay } from "swiper";
import Head from "next/head";
import Link from "next/link";

export default function FunWithGPT() {
    let images = [
        {
            src: "/images/gpt1.png",
        },
        {
            src: "/images/gpt2.png",
        },
        {
            src: "/images/gpt3.png",
        },
    ];

    return (
        <div className="project">
            <Head>
                <title>Fun with GPT-3</title>
            </Head>
            <div className="project-main">
                <div className="project-header">
                    <h1 className="project-title"> FunWithGPT-3 </h1>
                    <Link href="https://fun-with-gpt-3-nine.vercel.app">
                        <a className="project-link">
                            fun-with-gpt-3-nine.vercel.app
                        </a>
                    </Link>
                    <p className="project-description">
                        A web application built for Shopify's Frontend Developer
                        Intern Challenge. User can select from 4 AI engines to
                        use, can generate a random playlist based off of emojis
                        & also generate travel tips based off of input. All
                        results generated by Open AI's API.
                    </p>
                </div>

                <div className="project-about">
                    <h1 className="project-about_title">The Task</h1>
                    <p className="project-about_subhead">
                        An app that sends plain text prompts to the OpenAI API
                        and displays the results in a list.
                    </p>
                    <h1 className="project-about_title">Tech</h1>
                    <p className="project-about_subhead">
                        React, Next.js, Material UI, SCSS, Styled Components
                    </p>
                    <h1 className="project-about_title">My Role</h1>
                    <p className="project-about_subhead">
                        As this was a solo project, I handled everything. These
                        tasks included:
                    </p>
                    <div className="project-list">
                        <li className="project-list_item">
                            Reading through Open AI's API documentation to gain
                            a better understanding on how to use thier product.
                        </li>
                        <li className="project-list_item">
                            Researching color schemes & design patterns used by
                            Shopify and integrating them into my project.
                        </li>
                        <li className="project-list_item">
                            Set up Next.js API routes to handle fetching and
                            recieving data from API requests.
                        </li>
                    </div>
                </div>

                <Swiper
                    slidesPerView={1}
                    spaceBetween={20}
                    autoplay={{
                        delay: 6000,
                        disableOnInteraction: false,
                    }}
                    modules={[Autoplay, Navigation]}
                >
                    {images.map((img, i) => {
                        return (
                            <SwiperSlide key={i}>
                                <img src={img.src} alt="gpt-img" />
                            </SwiperSlide>
                        );
                    })}
                </Swiper>
            </div>
        </div>
    );
}
