import Head from 'next/head';
import Header from '../components/Header/Header';


export default function Home() {
  return (
    <div>
      <Head>
        <title>Cristopher Cunas</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
    </div>
  )
}
